### ISSUE TITLE
Distributed Roadmap

### ISSUE THREAD

**Issue by Fuyukai** [SunDwarf/curious#43]
I want to add the ability to split a bot up into several co-ordinating parts.

Essential processes:  
 - [x] Add ContextVar support to curio (see: dabeaz/curio#254)
    - Trio already has this (thanks to yours truly), so that's not an issue.

 - [x] Make dataclasses use a ContextVar for the bot object.
    - This makes them pickable, which means they can uploaded somewhere or sent over a network.

Curious core changes:

 - [ ] Change the eventbus API significantly.
   - To be decided on.

Then, a distributed wrapper will be made.
